# Добавьте эти строки в main.py после существующих регистраций команд

# ========== ИГРОВЫЕ КОМАНДЫ (ТРИ ВЕРСИИ: NEED, TRY, MORE) ==========

# VERSION: NEED
application.add_handler(CommandHandler("needadd", wordadd_command))
application.add_handler(CommandHandler("neededit", wordedit_command))
application.add_handler(CommandHandler("needstart", wordon_command))
application.add_handler(CommandHandler("needstop", wordoff_command))
application.add_handler(CommandHandler("needinfo", wordinfo_command))
application.add_handler(CommandHandler("needinfoedit", wordinfoedit_command))
application.add_handler(CommandHandler("needtimeset", anstimeset_command))
application.add_handler(CommandHandler("needgame", gamesinfo_command))
application.add_handler(CommandHandler("needguide", admgamesinfo_command))
application.add_handler(CommandHandler("needslovo", game_say_command))
application.add_handler(CommandHandler("needroll", roll_participant_command))
application.add_handler(CommandHandler("needrollstart", roll_draw_command))
application.add_handler(CommandHandler("needreroll", rollreset_command))
application.add_handler(CommandHandler("needrollstat", rollstatus_command))
application.add_handler(CommandHandler("needmyroll", mynumber_command))

# VERSION: TRY
application.add_handler(CommandHandler("tryadd", wordadd_command))
application.add_handler(CommandHandler("tryedit", wordedit_command))
application.add_handler(CommandHandler("trystart", wordon_command))
application.add_handler(CommandHandler("trystop", wordoff_command))
application.add_handler(CommandHandler("tryinfo", wordinfo_command))
application.add_handler(CommandHandler("tryinfoedit", wordinfoedit_command))
application.add_handler(CommandHandler("trytimeset", anstimeset_command))
application.add_handler(CommandHandler("trygame", gamesinfo_command))
application.add_handler(CommandHandler("tryguide", admgamesinfo_command))
application.add_handler(CommandHandler("tryslovo", game_say_command))
application.add_handler(CommandHandler("tryroll", roll_participant_command))
application.add_handler(CommandHandler("tryrollstart", roll_draw_command))
application.add_handler(CommandHandler("tryreroll", rollreset_command))
application.add_handler(CommandHandler("tryrollstat", rollstatus_command))
application.add_handler(CommandHandler("trymyroll", mynumber_command))

# VERSION: MORE
application.add_handler(CommandHandler("moreadd", wordadd_command))
application.add_handler(CommandHandler("moreedit", wordedit_command))
application.add_handler(CommandHandler("morestart", wordon_command))
application.add_handler(CommandHandler("morestop", wordoff_command))
application.add_handler(CommandHandler("moreinfo", wordinfo_command))
application.add_handler(CommandHandler("moreinfoedit", wordinfoedit_command))
application.add_handler(CommandHandler("moretimeset", anstimeset_command))
application.add_handler(CommandHandler("moregame", gamesinfo_command))
application.add_handler(CommandHandler("moreguide", admgamesinfo_command))
application.add_handler(CommandHandler("moreslovo", game_say_command))
application.add_handler(CommandHandler("moreroll", roll_participant_command))
application.add_handler(CommandHandler("morerollstart", roll_draw_command))
application.add_handler(CommandHandler("morereroll", rollreset_command))
application.add_handler(CommandHandler("morerollstat", rollstatus_command))
application.add_handler(CommandHandler("moremyroll", mynumber_command))

# СТАРЫЕ КОМАНДЫ (для обратной совместимости - перенаправляют на TRY)
application.add_handler(CommandHandler("add", wordadd_command))
application.add_handler(CommandHandler("edit", wordedit_command))
application.add_handler(CommandHandler("start", wordon_command))
application.add_handler(CommandHandler("stop", wordoff_command))
application.add_handler(CommandHandler("info", wordinfo_command))
application.add_handler(CommandHandler("infoedit", wordinfoedit_command))
application.add_handler(CommandHandler("timeset", anstimeset_command))
application.add_handler(CommandHandler("game", gamesinfo_command))
application.add_handler(CommandHandler("guide", admgamesinfo_command))
application.add_handler(CommandHandler("slovo", game_say_command))
application.add_handler(CommandHandler("roll", roll_participant_command))
application.add_handler(CommandHandler("rollstart", roll_draw_command))
application.add_handler(CommandHandler("reroll", rollreset_command))
application.add_handler(CommandHandler("rollstat", rollstatus_command))
application.add_handler(CommandHandler("myroll", mynumber_command))
